export const copy = {
  brand: {
    name: 'MovieMind',
    tagline: '你的私人观影空间',
    memberFallback: '影迷',
  },
  common: {
    close: '关闭',
    loadingApp: '正在进入你的私人影厅...',
    loadingMovieDetail: '正在加载电影详情...',
    previousPage: '上一页',
    nextPage: '下一页',
    pageLabel: (page, totalPages) => `第 ${page} / ${totalPages} 页`,
    unknownRelease: '上映日期待补充',
    noVotes: '暂无评分',
    votes: (count) => `${count.toLocaleString('zh-CN')} 人评分`,
    userAvatarAlt: '用户头像',
    profileAvatarAlt: '个人头像',
    fallbackTagline: '今晚值得加入片单的一部电影。',
  },
  nav: {
    items: [
      { label: '首页', to: '/' },
      { label: '发现', to: '/movies' },
      { label: '收藏', to: '/favorites' },
      { label: '我的', to: '/profile' },
    ],
    logout: '退出登录',
  },
  search: {
    placeholder: '搜索电影名称',
    heroPlaceholder: '搜索今晚想看的电影',
    button: '搜索',
  },
  auth: {
    login: {
      eyebrow: 'Now Showing',
      title: '回到你的电影空间，继续下一场观影。',
      subtitle: '登录后即可浏览影片、收藏想看内容，并留下自己的观后感。',
      submit: '登录',
      switchLabel: '还没有账号？',
      switchAction: '立即注册',
      switchTo: '/register',
      welcome: '欢迎回来',
    },
    register: {
      eyebrow: 'New Pass',
      title: '创建你的观影通行证，开始积累专属片单。',
      subtitle: '注册一次，即可保存收藏、记录评论，并持续沉淀自己的观影视角。',
      submit: '注册账号',
      switchLabel: '已经有账号了？',
      switchAction: '去登录',
      switchTo: '/login',
      welcome: '加入 MovieMind',
    },
    lead: '首期版本聚焦电影浏览、收藏与评论，先把核心观影体验跑通。',
    username: '用户名',
    password: '密码',
  },
  home: {
    eyebrow: 'Tonight',
    title: '今晚看什么，不该靠随机滚动，而该靠一眼就有感觉的选择。',
    description: '在更克制的界面里浏览电影、收藏想看的作品，并把每次观影后的感受留在自己的记录里。',
    featuredEyebrow: '精选片单',
    featuredTitle: '先从海报最有感觉的几部开始，再慢慢往里走。',
    openCatalogue: '查看完整片库',
    emptyTitle: '暂时还没有精选电影',
    emptyDescription: '当电影数据可用后，这里会优先展示最值得打开详情页的作品。',
    whyEyebrow: '为什么这样做',
    whyTitle: '首期围绕真正会发生的观影路径来设计。',
    highlights: [
      {
        title: '发现更直接',
        description: '首页和搜索页突出海报、氛围和关键信息，让你更快做出选择。',
      },
      {
        title: '收藏有记忆',
        description: '把想看和喜欢的电影留在自己的列表里，而不是淹没在信息流里。',
      },
      {
        title: '为 AI 预留空间',
        description: '首期先把服务层打稳，后续接入智能推荐时不用推翻重做。',
      },
    ],
  },
  movieList: {
    eyebrow: '发现',
    allTitle: '全部电影',
    resultsTitle: (keyword) => `“${keyword}” 的搜索结果`,
    description: '按片名搜索，先看海报和摘要，再决定是否进入详情页深入了解。',
    emptyTitle: '没有找到匹配的电影',
    emptyDescription: '可以换一个更宽泛的关键词，或者先回首页看看精选内容。',
  },
  movieDetail: {
    eyebrow: '电影详情',
    fallbackTagline: 'MovieMind 片库中的一部精选作品。',
    runtimeUnit: '分钟',
    favoriteAdd: '加入收藏',
    favoriteRemove: '取消收藏',
    favoriteSaved: '已加入你的收藏片单',
    favoriteUnsaved: '这部电影还不在你的收藏里',
    castEyebrow: '演员阵容',
    productionEyebrow: '制作信息',
    productionFallback: '制作信息暂未补充。',
    keywordsFallback: '暂无关键词信息。',
    producersFallback: '暂无制片人信息。',
    keywordsLabel: '关键词',
    producersLabel: '制片人',
    reviewsEyebrow: '评论',
    reviewsTitle: '写下你的观后感，也看看其他人是如何理解这部电影的。',
    emptyTitle: '还没有评论',
    emptyDescription: '你可以成为第一个留下观后感的人。',
  },
  favorites: {
    eyebrow: '收藏',
    title: '你的私人片单',
    description: '你标记过的电影都会留在这里，方便下一次继续挑选。',
    emptyTitle: '你还没有收藏电影',
    emptyDescription: '在电影详情页点击收藏后，这里就会出现你的私人片单。',
  },
  profile: {
    eyebrow: '我的',
    fallbackName: 'MovieMind 用户',
    fallbackBio: '这里先聚焦你的身份信息和评论记录，后续再逐步扩展个人空间。',
    uploadAvatar: '上传头像',
    uploadSuccess: '头像更新成功。',
    reviewsEyebrow: '我的评论',
    reviewsTitle: '你的观影记录',
    moviePrefix: '电影',
    emptyTitle: '你还没有发布评论',
    emptyDescription: '在任意电影详情页提交评论后，这里会显示你的观影记录。',
  },
  reviewComposer: {
    score: '评分',
    content: '影评内容',
    placeholder: '写下你对剧情、节奏、表演或某个瞬间的感受。',
    cancelEdit: '取消编辑',
    submitCreate: '发布评论',
    submitUpdate: '更新评论',
  },
  reviewActions: {
    edit: '编辑',
    delete: '删除',
  },
  flash: {
    loginSuccess: '欢迎回来，影厅已经为你准备好了。',
    registerSuccess: '注册成功，开始建立你的专属片单吧。',
    logoutSuccess: '你已退出登录，欢迎下次回来继续观影。',
  },
}
